spring.application.name=ecom



spring.datasource.url=jdbc:postgresql://localhost:5432/ecomdb
spring.datasource.username=embarkx
spring.datasource.password=embarkx
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto = update
spring.jpa.database-platform= org.hibernate.dialect.PostgreSQLDialect


